### ISSUE TITLE
Update supported stations to reflect wiki

### ISSUE THREAD

**Issue by roganartu** [bravecollective/bravecollective-freight#1]
Wiki: https://wiki.braveineve.com/member/freighting

Due to deployment, there are currently only 3 supported stations:
- [Zinkon VII - Moon 1 - Caldari Business Tribunal Accounting](http://evemaps.dotlan.net/station/Zinkon_VII_-_Moon_1_-_Caldari_Business_Tribunal_Accounting)
- [Defsunun IX - Moon 18 - Kaalakiota Corporation Factory](http://evemaps.dotlan.net/station/Defsunun_IX_-_Moon_18_-_Kaalakiota_Corporation_Factory)
- [Sakht VI - Moon 7 - Genolution Biotech Production](http://evemaps.dotlan.net/station/Sakht_VI_-_Moon_7_-_Genolution_Biotech_Production)

The website currently lists a bunch of stations that are no longer supported due to the deployment out of Catch.

The list of supported stations needs to be updated to reflect the wiki so users can easily calculate contracts again.

**Comment by roganartu** [comment]
#4

Haven't tested myself (I don't have a copy of the DB dump on my machine) but changes are pretty basic.

**Comment by kiu** [comment]
Sorry that I didnt react earlier. Incorporated a different pull request. Next time I will try to be on the ball.
