### ISSUE TITLE
Remove TEST from list of HERO-accessible stations

### ISSUE THREAD

**Issue by roganartu** [bravecollective/bravecollective-freight#2]
The file https://github.com/bravecollective/bravecollective-freight/blob/master/gen_stations/stations.py contains a list of what appears to be stations HERO should have access to.

I assume this is used to allow the frontend to determine whether BLT can run the contract or not.

In any case, TEST should probably be removed since they have since left HERO.

**Comment by kiu** [comment]
Done.
